### ISSUE TITLE
原生开发过程中如何使用wxp?

### ISSUE THREAD

**Issue by ipfans** [qiu8310/minapp#100]
目前小程序开发过程中支持npm包引入使用。

参考已有[文档说明](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html)，使用
```
npm install --production  @minapp/wx
```
安装wx后，使用

```javascript
import { wxp } from '@minapp/wx/wxp'
```

程序提示错误：

```
thirdScriptError 
 sdk uncaught third Error 
 module "@minapp/wx/wxp" is not defined 
 Error: module "@minapp/wx/wxp" is not defined
```

已勾选"使用npm模块功能"，SDK版本和开发工具版本均已符合要求。

是否是哪里遗漏掉了操作？

**Comment by qiu8310** [comment]
使用 wxp 方式没错，并且 wxp 相关的文件确实也存在；怀疑可能使用开发者工具的问题。

你可以试试使用其它 npm 包，看是不是一样有这种问题。

**Comment by csd998aaa** [comment]
我也是出了同样的问题
thirdScriptError 
 sdk uncaught third Error 
 module "pages/index/@minapp/wx/wxp" is not defined 
 Error: module "pages/index/@minapp/wx/wxp" is not defined
根目录有生成miniprogram_npm，但页面下的目录没有生成相关js

**Comment by csd998aaa** [comment]
> 使用 wxp 方式没错，并且 wxp 相关的文件确实也存在；怀疑可能使用开发者工具的问题。
> 
> 你可以试试使用其它 npm 包，看是不是一样有这种问题。

我也是出了这个问题
```
thirdScriptError 
 sdk uncaught third Error 
 module "pages/index/@minapp/wx/wxp" is not defined 
 Error: module "pages/index/@minapp/wx/wxp" is not defined
```
构建 后 项目根目录有生成`miniprogram_npm`这个文件。

**Comment by qiu8310** [comment]
我的包没有按照小程序的规范发布，这个包还是在小程序支持 npm 之前发的，所以不支持

你可以拉下源码来放你本地，另外那个包很多补全也没更新了，更新太麻烦，可以参考这个项目放你本地 https://github.com/wx-minapp/minapp-example-custom-wx
