### ISSUE TITLE
Interface 'BaseComponent<D, A>' cannot simultaneously extend types 'Component' and 'Options'

### ISSUE THREAD

**Issue by daolanfler** [qiu8310/minapp#102]
运行 tsc 控制台会提示这个错误：
![image](https://user-images.githubusercontent.com/29777079/50148531-b9dba980-02f3-11e9-866b-c5f3f85a3287.png)

**Comment by yuanjilee** [comment]
@daolanfler 怎么解决的，我也遇到这个。 编译时候执行 tsc，报错。
