### ISSUE TITLE
Promise<any>不存在finally属性

### ISSUE THREAD

**Issue by duyanren** [qiu8310/minapp#105]
![image](https://user-images.githubusercontent.com/20219141/51584711-763b1780-1f11-11e9-96db-8f968c7dc3a8.png)

**Comment by qiu8310** [comment]
你应该是参照这个项目 https://github.com/wx-minapp/minapp-example-custom-wx 把 wx 的定义都放本地了吧，那个项目里是没定义的。

你可以自行 import 下这个文件 https://github.com/wx-minapp/minapp-wx/blob/master/src/polyfill.ts

**Comment by duyanren** [comment]
我没有设置自定义类型示例，直接引入的是import { wxp } from '@minapp/core'

**Comment by qiu8310** [comment]
不好意思最近太忙了，没有注意到你的问题！

wxp 和 wx 的定义现在单独放到 `@minapp/wx` 中了， core 中找不到
