### ISSUE TITLE
example 跑不起来

### ISSUE THREAD

**Issue by stonelee** [qiu8310/minapp#108]
`@minapp/example-core-ts` 里面执行 `npm run dev`，会报错：

![image](https://user-images.githubusercontent.com/571863/52553009-2a4b0680-2e1d-11e9-9549-1059c5ecc4a6.png)

麻烦看下这个例子怎么跑起来，多谢

**Comment by qiu8310** [comment]
看提示，你应该是没有安装 `@minapp/component-demo`，安装一下即可。

不好意思，最近几天忙，没关注这边！

**Comment by stonelee** [comment]
我在这个库中单独安装依赖，确实就可以了。

之前是在主目录中执行 `lerna bootstrap`，这样自动安装的依赖是软链形式的，不知为何就会报错了~

多谢回复
