### ISSUE TITLE
初始化项目时，Style Lauguage选择less，会报错

### ISSUE THREAD

**Issue by liukunc9** [qiu8310/minapp#115]
![image](https://user-images.githubusercontent.com/40412682/59906119-7d237300-943a-11e9-9790-ef0fccb355a3.png)
初始化项目时，我的选择如上，然后我发现package.json中并没有less:
![image](https://user-images.githubusercontent.com/40412682/59905839-c6bf8e00-9439-11e9-87d8-2d5a108cb15a.png)
所以在执行yarn run dev时会报如下错误：
![image](https://user-images.githubusercontent.com/40412682/59905892-e951a700-9439-11e9-8473-3535e05741fd.png)

**Comment by qiu8310** [comment]
应该是第一步 minapp init 时没有执行完就关闭了（less 和 less-loader 是在项目初始化完成之后会自动安装的）

现在你手动安装下 less 和 less-loader 呗


BTW: 这个脚手架项目用的人不多，我现在也没放什么精力在这项目上

**Comment by liukunc9** [comment]
哦哦，好的，谢谢！！
