### ISSUE TITLE
scss文件中如何import node_modules中的wxss文件

### ISSUE THREAD

**Issue by zacksleo** [qiu8310/minapp#12]
按照scss中的使用方法，应该是 `@import "~wxParse/wxParse.wxss";` 但是不起作用，提示找不到文件

**Comment by qiu8310** [comment]
下个版本会支持，估计周末会发布。另外下个版本只需要 `@import "wxParse/wxParse.wxss";` 即可，不需要加 `~`

**Comment by zacksleo** [comment]
另外还有个问题,  不知道是否和这个问题相关, 由于[wxParse(https://github.com/icindy/wxParse)并没有在npm注册, 所以使用yarn 通过git方式安装wxParse库, 编译时并没有把wxParse加到dist/npm中

```
yarn add https://github.com/icindy/wxParse.git 
yarn run dev 
```

**Comment by qiu8310** [comment]
现在这个版本 scss 中只能 import scss，不支持 import 其它样式，所以不会编译到 dist 中

临时解决方案可以把 wxParse 样式后缀改成 scss 就可以（但有点要注意：编译器会把它上面的 px 单位自动转化成 rpx 单位）

这些问题下个版本会修复

**Comment by qiu8310** [comment]
不对，你还是不能在 scss 中引用其它样式，即使编译到了 dist 目录下，小程序也找不到它的引用！

scss 文件只能 import scss 文件，你需要把全局的样式写到 app.scss 中才行

**Comment by qiu8310** [comment]
@zacksleo 已经更新了一版

但是要注意，scss 文件中使用 import , sass loader 会把那个文件当作 sass 来用。
如果你在 css 或 wxss 中使用 import，才会触发将原文件移到 dist 目录下去
