### ISSUE TITLE
请教一下：导航栏 中文显示乱码的问题

### ISSUE THREAD

**Issue by gyl-coder** [qiu8310/minapp#122]
![image](https://user-images.githubusercontent.com/33021341/69786840-29416500-11f6-11ea-80a7-e47d8c454301.png)

请问你是如何解决的？

**Comment by qiu8310** [comment]
我没遇到，我猜你是在 window 系统上开发的吧，是不是保存的文件的编码不是 utf8 的？

**Comment by gyl-coder** [comment]
确实是这个问题，十分感谢
