### ISSUE TITLE
关于引入echarts的问题？

### ISSUE THREAD

**Issue by momtboy** [qiu8310/minapp#15]
echarts开发了小程序的引入，但是发现用此框架引入会报错！希望作者可以了解一下。急用！！！！！

**Comment by qiu8310** [comment]
你用的 minapp 是什么版本，报什么错误。

反馈下才好定位原因

**Comment by momtboy** [comment]
`i.measureText is not a function`

**Comment by momtboy** [comment]
作者可以看看 wepy等框架在引入echarts都会有不同的错误，希望作者能尽快给个方案。
[https://github.com/Tencent/wepy/issues/1010](https://github.com/Tencent/wepy/issues/1010)

**Comment by qiu8310** [comment]
最近 github 老慢了，一直登录不上。

看了下这个问题，确切的应该不是框架的问题，是配置文件问题，你需要把 `project.config.json` 中的 `libVersion` 指定到 `1.9.91` 以上(minapp 生成的默认值是 1.9.1)，如：

```json
{
   "libVersion": "1.9.91"
}
```

**Comment by qiu8310** [comment]
minapp 完全是原生的小程序开发，基本不会修改任何代码，所以引用其它为原生小程序开发的库应该不会出大问题。

这几天实在是访问 github 太困难了，我今天才成功把那个 echarts-for-wexin 的代码给拉下来

**Comment by momtboy** [comment]
作者引入echarts-for-wexin很正常运行？？？

**Comment by qiu8310** [comment]
![image](https://user-images.githubusercontent.com/1094697/37330764-11a7e47e-26dd-11e8-8ed2-2c2df510f65c.png)

你把那个 libVersion 升高点吧，低版本的微信 canvas 中没有 measureText 这个函数，所以才报你那个错误。

我感觉你不是很相信我 🤕

**Comment by momtboy** [comment]
`木有，我太马虎了，楼主辛苦咯`
