### ISSUE TITLE
如何在非 vscode 编辑器中自动创建 page 和 component 相关的文件

### ISSUE THREAD

**Issue by zacksleo** [qiu8310/minapp#16]
minapp 命令行工具支持编译一个 Component 或 Page 项目，但是不支持在指定目录新建component或page，由于不使用vscode开发，所以没有自动创建相关文件的功能，希望能通过命令实现

**Comment by qiu8310** [comment]
vscode 原生也不支持创建功能的，它要依赖 `dot-template-vscode` 实现的，好在 dot-template 提供了一个命令行的工具 `dot-template-cli`。

所以你可以使用这种方式来实现和 vscode 中一样的体验：

1. 先用 npm 全局安装 `dot-template-cli`

  ```bash
  npm install -g dot-template-cli
 ```
2. 然后在你项目的根目录上运行

 ```bash
  dtpl watch
  ```

你可以试下，有什么问题找我，那个 dot-template 也是我写的 [捂脸]

**Comment by zacksleo** [comment]
果然好使, 试试 👍
