### ISSUE TITLE
如何配置devserver的Proxy

### ISSUE THREAD

**Issue by zaaack** [qiu8310/minapp#17]

**Comment by qiu8310** [comment]
集成很简单，发个版本可以解决。

不过我想先了解下，我用 proxy 一般是有跨域问题时才用，小程序开发中的请求都是找 request 相关的函数吧，小程序中也没有本地服务器之说，proxy 有用吗？

**Comment by zaaack** [comment]
@qiu8310 有用，因为我们现在 API 还没准备好，不支持小程序，暂时只能用 App 的 API 开发。而 App 的 API 在 hybrid 项目中有一套模拟登录和验证的 proxy 方案。。。不过我觉得重点还不是某一项配置吧，如果能把 webpack 的配置暴露出来就好了。

**Comment by qiu8310** [comment]
我发个版本暴露所有 devServer 的配置吧

不过我现在发的是 1.x.x 版本，如果你用的是之前版本，要升级的

另外 1.x.x 版本根目录上支持 minapp.json 的配置文件

**Comment by qiu8310** [comment]
发布了 1.0.1 版本，你更新下 cli

根目录下加个 `minapp.cjson` 配置，内容可以如下

```json
{
  "$schema": "https://raw.githubusercontent.com/qiu8310/minapp/master/schema/minapp.json",
  "compiler": {
    "px2rpx": true, // 开启将 px 单位转化成 rpx 单位
    "rpx2px": false,
    "devServer": { // webpack-dev-server 相关的配置，详情参考：https://webpack.js.org/configuration/dev-server/
      "port": "9000"
    }
  }
}
```
