### ISSUE TITLE
scss 绝对路径?

### ISSUE THREAD

**Issue by zaaack** [qiu8310/minapp#18]
貌似目前只能这样引用

```scss
@import "../../../../../styles/common";
```

能不能这样

```scss
@import "styles/common";
````

**Comment by qiu8310** [comment]
哦，对，这应该是个问题， sass 使用的是 sass-loader 去解析，我没传 resolve-root 给它，所以它解析不了相对目录。 这个应该在 less 中也一样存在，我解决下。

谢谢！

**Comment by zacksleo** [comment]
@qiu8310 这个版本可以解决 #12 吗?

**Comment by qiu8310** [comment]
好像没用，上面的链接并不是最新的版本，我更改的代码在 minapp-compiler 中，而上面只有 cli 的代码。@zaaack  你用了吗？

**Comment by qiu8310** [comment]
@zacksleo  可以用这个版本，我试过了，这个可以解决， 不好意思，暂时不发版本了

```bash
 npm i -g http://lcdn.static.lotlot.com/minapp-cli-1.0.1-8796292a.tgz
```
