### ISSUE TITLE
怎么在vscode调试小程序

### ISSUE THREAD

**Issue by csonchen** [qiu8310/minapp#21]
你好，怎么让vscode编辑器跟小程序开发工具那样有面板可以调试小程序呢

**Comment by qiu8310** [comment]
这个不好实现的，还是老老实实用它开发者工具吧

**Comment by csonchen** [comment]
那你这个框架平常开发的时候要怎么调试的呀，文档好像没有写出来

**Comment by qiu8310** [comment]
调试还得在微信的工具上了，我这个框架只是个编译器，把代码编译成微信的工具上可以运行的代码（当然 minapp 还集成了一个简单的开发框架）

这个东西是完全不能替代开发者工具的

**Comment by csonchen** [comment]
好的，谢谢你，如果你能在README写出来就更好了~~

**Comment by qiu8310** [comment]
嗯，谢谢建议，回头我要更新下 README，我一向不擅长写文档
