### ISSUE TITLE
wx.d.ts 是如何生成的？

### ISSUE THREAD

**Issue by Allenice** [qiu8310/minapp#22]
wx.d.ts 是如何生成的？怎么样才能确保 minapp 提供的 wx.d.ts 与微信小程序的 api 同步？

**Comment by qiu8310** [comment]
所有 wx.d.ts 中的信息完全是从官方文档上抓起过来的，没任何手写的东西，代码在这里 https://github.com/qiu8310/minapp/tree/master/packages/minapp-generator/src

- `cli` 文件夹是命令行工具
- `generator` 文件夹是生成相关的脚本
- `modify` 文件夹是对官方文档的一个修证（比如错别字，文档重排之类的）

所以 wx.d.ts 完全是和官方文档同步的，而且可以随时更新（除非官方文档结构重新排版了）！


之前有考虑每个微信的版本生成一个 wx.d.ts，但考虑到官方文档其实也并没有很严格，而且官方文档上都注明了兼容版本号，所以就没那样做了。
