### ISSUE TITLE
编译报错！！

### ISSUE THREAD

**Issue by momtboy** [qiu8310/minapp#23]
λ minapp dev
events.js:183
      throw er; // Unhandled 'error' event
      ^

minapp v 1.0.1

**Comment by momtboy** [comment]
`[at-loader] Checking finished with 11 errors
Version: webpack 3.11.0
Time: 2559ms
PublicPath: http://localhost:8080/
  [20] ./src/app.cjson 891 bytes {0} [built]
  [47] ./src/pages/logs/logs.cjson 0 bytes {0} [built]
  [48] ./src/pages/logs/logs.scss 0 bytes {0} [built]
  [49] ./src/pages/logs/logs.ts 1.6 kB {0} [built]
  [51] ./src/pages/logs/logs.wxml 0 bytes {0} [built]
  [52] ./src/app.scss 0 bytes {0} [built]
    + 49 hidden modules

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:19:10
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'Tapable'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:19:19
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'HookMap'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:20:10
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'SyncBailHook'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:20:24
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'SyncHook'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:20:34
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'SyncLoopHook'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:20:48
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'SyncWaterfallHook'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:21:10
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'AsyncParallelBailHook'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:21:33
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'AsyncParallelHook'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:21:52
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'AsyncSeriesBailHook'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:21:73
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'AsyncSeriesHook'.

ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:21:90
    TS2305: Module '"D:/works/zhiyan/test-project/minapp-ts-update/node_modules/@types/tapable/index"' has no exported member 'AsyncSeriesWaterfallHook'.`

**Comment by qiu8310** [comment]
方便把你项目给我看看么，看上去像是路径有问题，导致webpack找不到对应的文件

**Comment by momtboy** [comment]
windows上面部署都会出现这个错误。。。

**Comment by qiu8310** [comment]
看上面错误好像是 webpack 中少了一些模块似的，要不你重装下 @minapp/cli 试试？

**Comment by momtboy** [comment]
npm和cnpm两种方式都尝试过，构建项目都会报错。。。

**Comment by qiu8310** [comment]
找到原因了，好像是因为 @types/tapable 模块在 3.10 号升级了，导致 webpack 找不到它内部的模块，我发个版本把它的依赖去掉吧

```
 @types/tapable
                  0.2.0  2016-11-04 01:43
                  0.2.1  2016-11-10 08:27
                  0.2.2  2016-11-30 08:20
                  0.2.3  2016-12-23 10:16
 ts2.2            0.2.4  2017-08-22 06:05
 latest           0.2.5  2018-03-10 10:21
 ts2.8            1.0.0  2018-03-10 10:21
```

**Comment by qiu8310** [comment]
新版 1.0.2 已经发布，我在 windows 验证已经不出现此问题了，谢谢反馈！
