### ISSUE TITLE
关于版本升级的指南。

### ISSUE THREAD

**Issue by momtboy** [qiu8310/minapp#24]
从0.9版本升级到1.0.2需要怎么做呢？希望作者能给一个升级指南的说明。

之前是用的0.9的版本搭建的，现在页面已经做了一大半了，在升级到1.0.2需要怎么操作呢？

谢谢！！！！

**Comment by qiu8310** [comment]
这一块我确实没有做好，先在这里简单和你说下吧：

从 0 -> 1 版本的升级，主要是把 mobx 模块抽离出来了，现在可以不依赖于 mobx 开发，另外支持了双向绑定，具体1版本的新功能可以看[这篇文章](https://qiu8310.github.io/minapp/blog/2018/03/10/release-v1.html)

**具体应该怎样升级呢？**

1. 用新的脚手架生成一个新的初始化项目（如果以前项目使用了 mobx，在初始化的时候也需要选择 mobx）
2. 用这个初始化项目的 src/base 目录下的文件替换之前 src/base 目录下的文件就行了（注意，如果你有修改 base 目录下的文件，则也需要注意恢复到新的 base 目录下）

这样改一下基本可以完成了，新版没有增加颠覆性的修改。主要可能是数据双向绑定可能对你有用，详情可以看上面的文章。


另外，感谢你使用 minapp，如果你不介意，可以加我微信 `qiu8310`，有什么问题可以直接微信上和我说，尽量帮你快速解决
