### ISSUE TITLE
1.0.2版本在windows下创建目录时无法自动创建文件。

### ISSUE THREAD

**Issue by momtboy** [qiu8310/minapp#25]
升级到1.0.2以后在vscode编辑器中pages目录下新建文件夹时，不会自动生成相应的文件。
vscode 已安装minapp 和 dot-template两个插件。
之前0.0.9的项目是可以生成的。

**Comment by qiu8310** [comment]
创建文件功能主要是 dot-template 这插件做的事，和 minapp 没关系，出现这种情况可能有两种原因：

1. vscode 没有启动 dot-template 服务（概率比较低，一般重启下 vscode 就有可能复原）
2. dot-template 运行错误（由于 dot-template 需要运行 .dtpl/dtpl.js 文件，所以此文件如果被修改了，或者语法有问题，都可能导致 dot-template 运行失败）


解决方案：
如果没有修改过 .dtpl/dtpl.js 文件，建议重启下 vscode 看能否正常；
如果修改过 .dtpl/dtpl.js 文件，建议复原下试试；
如果还是不行，则打开 vscode 的配置，添加一项配置

```json
"dot-template-vscode.debug": true
```
添加之后，重启下 vscode ，如果 dot-template 运行出错你的根目录会出现一个 `dtpl.error.log` 文件，看能否帮助你定位到原因。另外每次执行一个命令，都会把执行的详情写入到根目录的 `dtpl.debug.log` 文件中。这两个文件也许可以帮助你定位到原因，如果你解决不了，可以把这两个文件发给我。（另外，如果这两个文件压根就没生成，则肯定是上面说的第一个问题：vscode 压根就没有启动 dot-template 这个服务）
