### ISSUE TITLE
请问使用 cli 初始化的组件开发模式，在开发过程中如何查看效果？

### ISSUE THREAD

**Issue by Cphayim** [qiu8310/minapp#29]
考虑到通用的组件可以作为一个外部 npm 包导入，使用 cli 初始化了一个 component 项目，但是运行开发模式后发现在 dist 目录下生成的也只是这个组件的代码文件（组件显示需要页面载体），请问开发阶段应该让这个组件在开发者工具中运行查看效果？还有一个组件项目可以包含多个组件吗？

**Comment by qiu8310** [comment]
@Cphayim  不好意思，文档这块我做的一直都不好。

是的，单个组件你看不到任何效果，需要放到页面中，所以你需要先有一个页面的环境！如何使用你正在开发的组件可以有下面几种我知道的方法：

1. 使用 [lerna](https://github.com/lerna/lerna) 工具将你的 Component 项目和 Application 项目放一起（有一定的门槛）
2. 在你 Application 项目中使用 link 文件，link 到 Component 项目
3. 使用 `npm link` 命令，可以看[这里](https://github.com/atian25/blog/issues/17)
4. 在你开发 Component 项目时，可以指定 `distDir`，将它指定到你 Application 项目的 components 目录即可（这可能是最简单的方案）
