### ISSUE TITLE
cjson编译以后报错!!

### ISSUE THREAD

**Issue by momtboy** [qiu8310/minapp#3]
src里面的cjson文件编译以后  路径变成了  \\  微信开发工具报错

**Comment by qiu8310** [comment]
我知道了，我刚发布的 0.0.7 版本为了支持 node_modules 文件夹中的组件，把 json 文件中的路径处理了。 没有在 window 上测试，不好意思， window 上可能还会有些其它问题。

非常感谢你的反馈！已经更新到0.0.9了，你重装一下就可以了 `npm i -g @minapp/cli`

**Comment by qiu8310** [comment]
@momtboy  我在 window 上测试不是太方便，麻烦有什么问题可以给我及时反馈，再次感谢
