### ISSUE TITLE
可否导出微信 api 里面类型的定义，如 CanvasContext？

### ISSUE THREAD

**Issue by fengcen** [qiu8310/minapp#30]
经常需要使用微信里面的结构，但是 minapp 好像没有导出这些结构，只能使用 any 替代，可否添加 export 导出？

**Comment by qiu8310** [comment]
没明白，能具体点吗？canvasContext 我记得有一个专门的 class 的

**Comment by fengcen** [comment]
我有一个class:
```
import { CanvasContext } from '@minapp/core';  // 这行代码报错，提示“没有导出的成员 CanvasContext”

class Canvas {
  ctx: CanvasContext;  // 想使用这个类作为 ctx 的类型，否则用 any 的话没有智能提示

  constructor(canvasId: string, instance: any) {
    this.ctx = wx.createCanvasContext(canvasId, instance);
  }

  add(image: Image) {
    this.ctx.drawImage(image.url, image.x, image.y, image.width, image.height); 
    this.ctx.draw();
  }
}
```

**Comment by qiu8310** [comment]
哦，这个已经有了，全在 wx 这个命名空间里，比如 wx.CanvasContext

其实，所有的 interface 你都能在 wx 中找到，比如 request 函数参数是 wx.request.Param 类似，总之 request 函数的所有相关 interface 都在 wx.request. 中

**Comment by qiu8310** [comment]
其它情况都类似，你自己去体验一下，很容易找到我的命名规律的   


wxp 中也类似

**Comment by fengcen** [comment]
谢谢，找了一下没找到 o(╯□╰)o

**Comment by qiu8310** [comment]
@fengcen  这个我确定有的，我这几天不方便用电脑。 你可以在这文件里找找 https://github.com/qiu8310/minapp/blob/master/packages/minapp-core/typing/wx.d.ts

**Comment by fengcen** [comment]
找到了，刚才说的是之前没找到，囧

**Comment by qiu8310** [comment]
好吧，我理解错了 😀
