### ISSUE TITLE
本地图片 以及 wxss 中转成 base64 图片?

### ISSUE THREAD

**Issue by zaaack** [qiu8310/minapp#31]
https://qiu8310.github.io/minapp/docs/doc-attention-on-build.html

对于很多小型 小程序图片资源并不多，如果能一起打包的话不仅开发更加简单，而且加载速度也更快。

**Comment by qiu8310** [comment]
嗯，这个可以有。

你觉得我在 样式中加个 data 函数如何，比如： 

```css
background: data(path/to/img)
```

**Comment by zaaack** [comment]
可以, 只要能实现就好。因为我看了下我们的小程序，加起来才只有400多k, 完全没有必要把 图片单独上传到cdn, 即使有需要的时候，几bk大小的图片inline的话也是比较合适的。。

**Comment by fengcen** [comment]
可以实现为类似 url-loader，添加 limit 选项，在 limit 以内的转为 base64

**Comment by Hoyoe** [comment]
@qiu8310 这个主意不错！希望可以尽快添加

**Comment by qiu8310** [comment]
@zaaack  @fengcen  @Hoyoe  

都加上了，可以在 minapp.json 中配置 `urlLoaderLimit` 来自动将图片转为 base64，也可以用 data 函数手动处理

详情参考： https://qiu8310.github.io/minapp/docs/doc-about-style.html

**Comment by qiu8310** [comment]
更新 `@minapp/cli` 到 1.0.6 即可

**Comment by fengcen** [comment]
好的，谢谢

**Comment by fengcen** [comment]
这个功能有测试吗，好像我无论 urlLoaderLimit 怎么设置 wxml 里面的图片都没有转成 base64 的格式

**Comment by zacksleo** [comment]
@qiu8310  urlLoaderLimit  对 wxml里面的 <image> 标签，起作用吗？

**Comment by zaaack** [comment]
会
