### ISSUE TITLE
自定义组件如何使用全局样式？

### ISSUE THREAD

**Issue by Allenice** [qiu8310/minapp#32]
微信小程序自定义组件可以通过 @import 的方式引入样式，但是项目中使用 sass, @import 的时候会将代码生成到对应的文件， 这样会使代码重复了。

**Comment by qiu8310** [comment]
这是sass的功能，没办法，除非你用 css 或 wxss 就可以复用。

或者你把公用的样式放在 app.sass中，这样都不用 import
或者你在公用的 sass 中只放 mixin

**Comment by Allenice** [comment]
公共样式放到 app.scss 中，这些公共样式是不能用在自定义组件的。是否可以考虑通过 loader 和注释的方式将 wxss 引入到自定义组件里面？

**Comment by Allenice** [comment]
或者可以给一个选项，自定义组件的 wxss 默认 import "app.wxss"

**Comment by qiu8310** [comment]
@Allenice  想尝试做的，确实也可以做到，但实现方法不是很好，有点 hack，打算算了。

用 sass 的话就考虑在公共的地方用 mixin 吧，不要在公共的 sass 中写具体的 class

**Comment by qiu8310** [comment]
因为修复一个 bug，把这个 issue 修好了！

scss 中可以使用注释的方式来达到你要的效果（import 中的文件不合并到一个文件，而是把它保留原有文件）

```scss
/*! @import "path/to/your/file.scss"; */
```
**注意：注释格式只能如上面示例的样式，最后也需要有个分号，且一个注释中只能写一个 import**

这个功能我还没有公开。
