### ISSUE TITLE
ts有类型错误好像就不编译了

### ISSUE THREAD

**Issue by AlexStacker** [qiu8310/minapp#35]
今天开始用minapp+ts写小程序，碰到一个参数类型是any的错误，控制台提示类型错误
![image](https://user-images.githubusercontent.com/7822744/37861351-d9652830-2f72-11e8-9536-17d35d7e7119.png)
然后微信开发工具没有刷新出编译后的js了，我觉得这个是不是有点严格了，类型错误报错就好，但是应该继续编译。

**Comment by fengcen** [comment]
这个是可以通过 tsconfig.json 配置的，你可以关掉这个限制，但是一般来说用 ts 最好还是养成好习惯。

**Comment by qiu8310** [comment]
是的，这是 ts 语言的特性，你可以将 tsconfig.json 中的 `noImplicitAny` 的值设置成 `false` 就好了

**Comment by AlexStacker** [comment]
平时写vue的时候也会碰到类型错误的，但是基本上也都编译产生了js文件，这次minapp感觉好像并没有产生，让我习惯性改完不等实时编译结束就去看浏览器结果有点不习惯。

**Comment by qiu8310** [comment]
@AlexStacker  这应该是 awesome-typescript-loader 的功能，你试试在 `tsconfig.json` 中加个配置项：

```json
"awesomeTypescriptLoaderOptions": {
    "errorsAsWarnings": true
 }
```

更多详情可以看 [awesome-typescript-loader 主页](https://github.com/s-panferov/awesome-typescript-loader)

**Comment by AlexStacker** [comment]
确实可以，但是还是感觉怪怪的...哈哈
