### ISSUE TITLE
关于Page中缺失的一些方法

### ISSUE THREAD

**Issue by masonz** [qiu8310/minapp#36]
Hi, 我发现在Page中其实也有selectComponent/selectAllComponents的方法来获取自定义组件的实例，但目前typings里好像暂无相关定义?

**Comment by qiu8310** [comment]
这个不是在 Page 中，是在 Component 中的 https://mp.weixin.qq.com/debug/wxadoc/dev/framework/custom-component/component.html

typings 中已经有了： https://github.com/qiu8310/minapp/blob/master/packages/minapp-core/typing/component.d.ts#L130-L133

**Comment by masonz** [comment]
微信文档无明确说明Page中也存在同样的方法，我在开发过程中有时需要在Page里获取组件实例，经过验证也是可以通过selectComponent/selectAllComponents的方法来获取的

**Comment by qiu8310** [comment]
看了下，好像确实，而且组件里的方法基本上都有，还包括 `getRelationNodes` 等，我下个版本加上吧。

谢谢！
