### ISSUE TITLE
［建议］小程序标签补全冲突

### ISSUE THREAD

**Issue by bigmeow** [qiu8310/minapp#39]
在 vue 模板文件中，需要指定 template 的 lang="wxml"就能自动补全，
但是不少其他的脚手架工具，比如mpvue的，如果把模版的template的lang改了，会报错，因为默认lang是html。
希望换个自定义属性也能支持补全，比如
在 vue 模板文件中，需要指定 template 的 minapp="true"就能自动补全，
```
<template minapp="true"></template>
```

**Comment by qiu8310** [comment]
这样啊，没有 mpvue。 不过你的建议可行，我下个版本加上。

**Comment by qiu8310** [comment]
@bigmeow  已经支持了，需要使用 `minapp="mpvue"`  或 `lang="mpvue"`

注意，如果使用 `minapp="mpvue"` 的话，你的文件还是 html，所以你的模板中会同时存在 vue 和 minapp 的补全

![vue](https://user-images.githubusercontent.com/1094697/38163107-e0567672-3520-11e8-875e-239f10af6aef.gif)
