### ISSUE TITLE
能否扩大 minapp-vscode 的使用范围

### ISSUE THREAD

**Issue by netputer** [qiu8310/minapp#4]
插件 `minapp-vscode` 的使用前提好像是将文件的「语言模式」调为 `WXML`，但我项目使用的是 `min` 且对应的「语言模式」是 `Vue`，好像就没法使用 `minapp-vscode` 了… 

有方法扩大插件的使用范围么，而且将来 `minapp` 也推 SFC 的话也应该需要这种支持

**Comment by qiu8310** [comment]
是的，这个可以在 vue 提供的那个插件中让它支持 wxml 语言的，vue-loader 中可以指定 `<template lang="pug"></template>` 就可以实现 pug 的自动补全，其实让它实现 wxml 也是一样的，只是可能需要去了解下它的 vscode 插件 https://github.com/vuejs/vetur 。

这个我是计划做的，但我当下计划是做其它一些事，你有兴趣也可以去研究下。

**Comment by qiu8310** [comment]
@netputer  minapp-vscode@1.0.4 已经支持了在 vue 自动补全，你可以下载试用。

使用方法需要在 vue 模板的 template 中指定 lang="wxml"，如

```html
<template lang="wxml">
...
</template>
```

**Comment by AlexStacker** [comment]
支持pug和pug的补全吗?特意来问的[手动微笑脸]

**Comment by qiu8310** [comment]
@AlexStacker 我目前没那个计划，只能期待 pr

**Comment by AlexStacker** [comment]
怎么提供，很想试试😄

**Comment by qiu8310** [comment]
@AlexStacker  我新开了一个 issue，见 #34 。如果你真有意愿开发，我们可以详细交流，可以加我微信 `qiu8310`

**Comment by qiu8310** [comment]
@netputer  @AlexStacker  minapp 的 vscode 已经支持 pug 自动补全了，并且 minapp 框架也支持 pug 语言

**Comment by AlexStacker** [comment]
我又要拉取大佬的代码学习了

**Comment by netputer** [comment]
`<template lang="wxml"></template>` 亲测可用，感谢作者～

另外想问下，有可能将 `wx` `wxp` 的支持独立出来么

**Comment by qiu8310** [comment]
@netputer  我猜你应该使用了 wepy 或者 mpvue 框架，你可以再在 template 上加个参数，更精确的使用对应框架的自动补全，详情查看 https://github.com/qiu8310/minapp/tree/master/packages/minapp-vscode#vue

**Comment by netputer** [comment]
这个很贴心，我用的是 min，靠 `<template lang="wxml"></template>` 已经可以补全了
