### ISSUE TITLE
webpack 4 的升级计划

### ISSUE THREAD

**Issue by thewei** [qiu8310/minapp#40]
不知道什么时候会升级到 webpack 4 呢，另外 cli 能否暴露可自定义 webpack 的配置。

**Comment by qiu8310** [comment]
devServer 全部暴露了，你还需要什么，我看可不可以考虑集成进去？

**Comment by thewei** [comment]
比如开发、发布时编译的环境变量如何设置

**Comment by qiu8310** [comment]
@thewei  这个已经有了，`__ENV__` 是个全局变量（vscode 可以自动提示的），可以是 development 和 production

**Comment by thewei** [comment]
很多时候还需要自己添加一些环境变量，所以这框架现在还不是很灵活

**Comment by fengcen** [comment]
有开放 webpack 配置的计划吗，发现我也有定制 webpack.config 的需求

**Comment by qiu8310** [comment]
升级到4的时候再考虑这个了，近期公司项目也是紧😂

**Comment by qiu8310** [comment]
@thewei  @fengcen   webpack 配置已经暴露了，但升级到 4 估计暂时不太能实现，详情看 https://qiu8310.github.io/minapp/docs/doc-custom-webpack.html

**Comment by qiu8310** [comment]
v2 已经更新到 webpack 4 了， v1 升级到 v2 查看此文档： https://qiu8310.github.io/minapp/docs/doc-update-v1-to-v2.html
