### ISSUE TITLE
minapp build 没有读取 NODE_ENV

### ISSUE THREAD

**Issue by fengcen** [qiu8310/minapp#45]
运行 `minapp build --publicPath http://localhost:3000` 的时候，NODE_ENV 始终是 production，使用 `cross-env NODE_ENV=beta` 设置无效，但是 `minapp dev`的时候 NODE_ENV 的值是正确的。

**Comment by fengcen** [comment]
可以改成没有设置 NODE_ENV 则默认是 `production`，否则应该使用手动设置的 NODE_ENV。因为有时候我需要打内网包，如果都是 `production` 无法区分应该请求哪个域名。

**Comment by qiu8310** [comment]
你应该是想自定义环境变量吧，不一定是 NODE_ENV

**Comment by fengcen** [comment]
对的，但是现在只用到了 NODE_ENV，现在有办法可以支持吗

**Comment by qiu8310** [comment]
你可以修改我的代码，在 @minapp/compiler/dist/config/webpack.config.js 中，在 webpack.DefinePlugin 处添加其它变量

我下个版本想办法开放 webpack 配置吧

**Comment by qiu8310** [comment]
如果项目是你一个人做这样最方便，多个人的话就只能等我下个版本

**Comment by fengcen** [comment]
好的，我先临时自己改一下，麻烦了

**Comment by qiu8310** [comment]
@fengcen  已经支持了，详情查看 http://localhost:3000/minapp/docs/doc-custom-webpack.html

**Comment by qiu8310** [comment]
所有配置都暴露了，你修改自己小心点

**Comment by fengcen** [comment]
好的，谢谢。
