### ISSUE TITLE
怎么将这个项目跑起来

### ISSUE THREAD

**Issue by fengcen** [qiu8310/minapp#49]
如果我想做一些修改，然后使用 `npm link` 将项目跑在本地，需要什么步骤？
试了一下编译发现 ts 报了非常多的错误，minapp-common 里面的 `./Component` 找不到，并且这个文件是放进了 `.gitignore`，不清楚意图。

**Comment by qiu8310** [comment]
在目录下运行 `node src/dev/script.js dev` 可以生成那个文件

那个文件是 Component 相关的定义，之前会有两个不同的版本(可以看上面的 script.js 脚本了解)，现在基本上只用 dev 版本了，我也一直没更新
