### ISSUE TITLE
使用wepy之后,文件名会变成 .wpy  触发不了自动补全

### ISSUE THREAD

**Issue by a245501835a** [qiu8310/minapp#54]
如题

**Comment by qiu8310** [comment]
你需要把 .wpy 文件关联到 vue 的格式才可以

**Comment by a245501835a** [comment]
@qiu8310  你好，我按照wepy官网文档上面设置的已经关联到vue格式了，代码都呈现为高亮

**Comment by a245501835a** [comment]
@qiu8310  但是还是没用 [捂脸]

**Comment by qiu8310** [comment]
看看这个 https://github.com/qiu8310/minapp/blob/master/packages/minapp-vscode/README.md#vue  和 #51

**Comment by a245501835a** [comment]
@qiu8310  好的谢谢！
