### ISSUE TITLE
为什么不覆盖 setData 方法，而去添加一个新方法？

### ISSUE THREAD

**Issue by chemzqm** [qiu8310/minapp#57]
其实可以给 compiler 加个 babel 的插件，让 babel 吧 setData 方法转成 setDataSmart

**Comment by qiu8310** [comment]
用babel转化不太好做吧：
万一用户取了一个 setData 的别名；
用户也可以自己在某个独立的文件里定义setData方法！

还是有很多东西要考虑的，不太容易实现

**Comment by chemzqm** [comment]
嗯，不太好，我想了下其实有些情况是不想用 setSmartData 的，所以最好还是不要覆盖原来的方法。
