### ISSUE TITLE
建议： minapp-cli 使用项目内构建工具

### ISSUE THREAD

**Issue by chemzqm** [qiu8310/minapp#58]
目前 minapp-cli 使用的是全局安装包，这样会导致 minapp-cli  升级之后旧项目可能无法编译的问题，建议学习 gulp 以及 webpack 方式，调用本地安装的依赖包进行构建。

**Comment by qiu8310** [comment]
其实也可以本地安装，通过 npm script 去调用 minapp 命令，这样它会去读取本地安装的命令

不过你说的这个要实现其实也蛮简单，我担心 minapp-cli 中的依赖包太多了 [捂脸]

**Comment by qiu8310** [comment]
v2 已经实现了
