### ISSUE TITLE
需求：支持自定义 .babelrc 和 postcss.config.json

### ISSUE THREAD

**Issue by chemzqm** [qiu8310/minapp#59]
这样用户可以扩展 babel 和 postcss 的能力，配置可以进行合并，或者简单点如果用户配置了就使用用户的配置。

**Comment by qiu8310** [comment]
嗯，有考虑过

不过这个要等到我把 webpack 升级到 4 再一起做了吧

**Comment by qiu8310** [comment]
这个之前也看过别人的实现，好像要考虑太多东西，然后我就放弃了 ...

**Comment by chemzqm** [comment]
可以简单点，容许用户在配置文件中添加相关配置，实际构建的时候把配置进行合并就可以了

**Comment by thewei** [comment]
webpack 4 的升级启动了吗

**Comment by qiu8310** [comment]
@thewei  要等我有时间，这段时间工作挺忙的

**Comment by qiu8310** [comment]
v2 已经实现，不过统一需要在 webpack.minapp.js 中修改，参考 https://qiu8310.github.io/minapp/docs/doc-custom-webpack.html#minapp-v2-loader-loader
