### ISSUE TITLE
能否在国内的码云上也推一份。

### ISSUE THREAD

**Issue by luogeng2017** [qiu8310/minapp#6]
很喜欢你的项目，自己也非常喜欢TS。只是国外网速有点忙，有时候公司的网还上不去，能不能在码云上也推一份代码，谢谢啦

**Comment by qiu8310** [comment]
你是说 https://coding.net 吗？

**Comment by zaaack** [comment]
@qiu8310 我猜他说的是 gitee.com

**Comment by qiu8310** [comment]
第一次听说 gitee，不过这个真的有必要吗？其实 github 在国内还是蛮快的吧，我这边没有很慢的感觉

**Comment by zaaack** [comment]
@qiu8310 gitee 是开源中国的免费 git 服务，比 coding.net 厚道许多，无论私有还是开源项目每人最多支持 1000 个 repo, 而且可以自动导入 GitHub，你可以申请推荐项目，可以获得更多关注。
 https://gitee.com/explore/recommend

**Comment by qiu8310** [comment]
@luogeng2017  同步了一份  https://gitee.com/mora/minapp

**Comment by qiu8310** [comment]
@zaaack 它们对推荐项目要求还是蛮高的，算了。 我还是比较习惯了 github

**Comment by zaaack** [comment]
@qiu8310 ... 不会把，我两个项目都上了推荐 https://gitee.com/zane_young/

**Comment by qiu8310** [comment]
> 项目官网显著位置标注该项目的码云链接地址
> 项目相关新闻、文章分享中如涉及项目源码，需使用码云地址
> 协作开发人数至少 5 人
> 提供完善的文档
> 用户评价(Star) >= 100

@zaaack 它的要求不用全满足？

**Comment by zaaack** [comment]
不用吧，先提交了再说 /捂脸

**Comment by luogeng2017** [comment]
蟹蟹大侠！ @qiu8310
