### ISSUE TITLE
Feature Request: 将 page 父类的 data 属性与 page 本身的 data 进行合并

### ISSUE THREAD

**Issue by chemzqm** [qiu8310/minapp#60]
这样更有助于将共用的逻辑抽象到父类，建议使用 https://www.npmjs.com/package/merge 的 recursive 方法将子类 data 递归的覆盖父类的 data。

**Comment by qiu8310** [comment]
这个框架用的是 class 的方式，所以如果子类和父类都有 data 属性的话，在 class 中子类会覆盖掉父类的 data 属性。所以这个不太好实现。

**Comment by qiu8310** [comment]
先关闭了，这个应该不会实现
