### ISSUE TITLE
安装第三方包打包成功，生成代码却存在问题

### ISSUE THREAD

**Issue by zhaoqinghai** [qiu8310/minapp#65]
![default](https://user-images.githubusercontent.com/26404526/39577110-f8cd9c56-4f12-11e8-8abb-3a20904748a2.png)

**Comment by qiu8310** [comment]
怎么复现，简单描述下

**Comment by zhaoqinghai** [comment]
先通过cnpm安装rxjs6.0的包，然后引用rxjs到项目中，再输入minapp dev 生成成功，没有异常。再打开微信小程序开发工具将生成的dist引入其中 运行就会出现这个问题

**Comment by qiu8310** [comment]
怎么引用的 rxjs，我直接 require('rxjs') 没什么问题，是不是调用了什么函数或者什么的触发了？

**Comment by zhaoqinghai** [comment]
我是这样引用的import * as Rx from 'rxjs'; 没调用其他函数

**Comment by qiu8310** [comment]
我没办法复现

![image](https://user-images.githubusercontent.com/1094697/39616259-136f2404-4fad-11e8-8985-73ef4ee3b047.png)

![image](https://user-images.githubusercontent.com/1094697/39616247-0ba7cf0a-4fad-11e8-95dd-a2c3ac8783ab.png)

你用的 minapp/cli 是什么版本

**Comment by zhaoqinghai** [comment]
那为什么显示的是本地服务的js无法加载，是不是还要设置防火墙。能不能直接相对路径引入呢

**Comment by zhaoqinghai** [comment]
这个文件是不存在的，是有哪个地方需要这个文件吗

**Comment by qiu8310** [comment]
那我不太清楚，你重装下 rxjs 试试，我这边是正常运行的

**Comment by zhaoqinghai** [comment]
我装了好几次了,也装了好几个版本了,今天minapp又升级到2.0了,可还是编译成功了，在微信小程序开发工具就报错

**Comment by qiu8310** [comment]
你是 window 系统吗？

**Comment by zhaoqinghai** [comment]
对啊 win10

**Comment by qiu8310** [comment]
好，我去 window 下试试看

**Comment by zhaoqinghai** [comment]
好的，谢谢啦

**Comment by zhaoqinghai** [comment]
谢谢 成功了
