### ISSUE TITLE
更新到v2.0版本后，wxp 不显示提示

### ISSUE THREAD

**Issue by Hoyoe** [qiu8310/minapp#67]
按照指南将v1.x 的项目升级到了 v2.0 版本
使用中发现两个问题

* `wxp.方法` 不会提示了，别的如 `wx.方法` 提示正常
* 开发模式下每次代码修改就会重新覆盖 `project.config.json`，导致在开发者工具内“添加编译模式”的内容消失（之前是每次`npm run dev`时覆盖一次）

**Comment by Hoyoe** [comment]
```json
{
  "dependencies": {
    "@minapp/core": "^2.0.0",
    "@minapp/wx": "latest"
  },
  "devDependencies": {
    "@minapp/cli": "^2.0.1",
    "babel-runtime": "^6.24.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1"
  }
}
```

**Comment by qiu8310** [comment]
第一个问题解决了，你执行下 `npm upgrade @minapp/wx` 即可。
第二个问题我稍后看看

**Comment by qiu8310** [comment]
第二个问题临时解决方案是，你每次添加完编译模式就把 dist 中的 project.config.json 复制到 src 目录中

**Comment by Hoyoe** [comment]
好的
