### ISSUE TITLE
请问 LICENSE 是 MIT LICENSE 吗？

### ISSUE THREAD

**Issue by yuche** [qiu8310/minapp#69]
我看到部分源码有写是 MIT LICENSE，但是项目根目录和 GitHub 设置都没有指定 LICENSE。
还是能希望能确定一下为好。

**Comment by qiu8310** [comment]
是的。
好的，在中国 LICENSE 意识不强

**Comment by yuche** [comment]
看了一下代码质量，的确非常高。非常感谢能提供 MIT LICENSE。加油~
