### ISSUE TITLE
minapp-wx下的page.d.ts声明中onShareAppMessage返回的回调类型错误

### ISSUE THREAD

**Issue by moesuiga** [qiu8310/minapp#73]
![_15275043897369](https://user-images.githubusercontent.com/28630067/40611066-75907298-62a7-11e8-8b50-6ab29e5d7449.png)
如图，回调类型写的是string

**Comment by qiu8310** [comment]
失误😅  你可以发个 pr 吗

**Comment by qiu8310** [comment]
更新了，微信现在也不支持回调了，我把那三个参数去掉了
