### ISSUE TITLE
请问, event的定义没找到, 还没有定义吗?

### ISSUE THREAD

**Issue by cfcodefans** [qiu8310/minapp#76]
onClickOpenButton(**e: any**) {
    // 轻松修改全局数据
    this.store.userInfo = e.detail.userInfo

    // 组件内数据还是用 setData
    this.setDataSmart({motto: '点击了『获取头像昵称』按钮'})
  }

**Comment by qiu8310** [comment]
没有 Event 的定义

因为我在官方文档上没看到有这一块定义，所以不敢确定所有的 Event 结构都一样，你可以自己定义一个在你项目中即可
