### ISSUE TITLE
webpack编译到ES6 prod，再用微信IDE编译到ES5时可能报错

### ISSUE THREAD

**Issue by jokester** [qiu8310/minapp#78]
为什么不一步编译到ES5: TypeScript编译async函数到ES6时会是 `function *` + helper的形式，到ES5时则直接生成状态机。前者人类比较易读。

报错原因是微信IDE的ES6编译需要`import regeneratorRuntime from 'regenerator-runtime'` 且regeneratorRuntime 不能被更名。但是目前的webpack uglify设置会导致regeneratorRuntime在prod build被更名。

有什么比较方便的解决吗？

**Comment by qiu8310** [comment]
Uglify 的配置写死了，不过你可以在 minapp.webpack.js 里将默认的 uglify 去掉，定义一个你自己的 uglify 配置，默认的配置你可以参考这个文件 https://github.com/qiu8310/minapp/blob/master/packages/minapp-cli/src/config/webpack.config.ts


不过我还是要问下，既然是dist目录，又何必在乎它的可读性？

**Comment by jokester** [comment]
谢谢你的提示

确实不是个很重要的需求.. 最多是在微信那个IDE中读代码和debug能方便点。先关掉好了。
