### ISSUE TITLE
如果不用mobx, 应该怎么做

### ISSUE THREAD

**Issue by zacksleo** [qiu8310/minapp#8]
如果不使用mobx, 应该怎么清理

**Comment by qiu8310** [comment]
这一块我还没考虑，你用 @minapp/mobx 框架就一定有 mobx

不过你可以只用 @minapp/core 这个模块，这里有所有 wx 和 wxp 的自动补全，但你没办法使用 @appify 或 @pagify 这些函数

如果你实在也想用 @appify 和 @pagify 这些东西，我建议你看看 @minapp/mobx 这里面的代码，其实没写什么，你完全可以复用

最后，问下你，为什么不想用 mobx 呢？是不需要全局的数据吗？或者什么其它原因？

**Comment by zacksleo** [comment]
不用mobx, 主要是因为对mobx不熟悉, 另外页面逻辑比较简单, 应该不需要全局数据

**Comment by qiu8310** [comment]
这样呀，那你可以就把 store 放在那里别去调用就行了，说不定你以后要用一个全局数据呢？

其实 mobx 很简单的，有机会我写篇文章介绍下。

**Comment by zacksleo** [comment]
ok, 那我先尝试一下

**Comment by zaaack** [comment]
同问，不想用 mobx ，想用自研的全局状态管理库咋办。。

**Comment by qiu8310** [comment]
@zacksleo  下个版本直接使用 @minapp/core 就可以

周末发布下个版本

**Comment by qiu8310** [comment]
@zacksleo @zaaack  已经更新 1.0.0 版本了，你们重新安装下 `@minapp/cli`，再使用 `minapp init` 即可以获取到不用 mobx 的初始化项目

**Comment by zaaack** [comment]
@qiu8310 不用 mobx 时 appify 貌似报了一个 warnning:

```
VM323:1 用 appify 函数时没有提供 store，需要提供；或者将 %o 装饰器中的 observe 属性指定为 false function default_1() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.properties = {
            message: {
                type: String
            },
            visible: {
                type: Boolean
            },
            timeout: {
                type: Number,
                value: 5
            }
        };
        _this.data = {
            count: 0
        };
        return _this;
    }
```

**Comment by qiu8310** [comment]
我觉得应该是你的 base 目录下的 MyApp 继承了 MobxApp，应该继承 `@minapp/core` 中的 BaseApp

现在它们分离了，你看看是不是

**Comment by zaaack** [comment]
貌似没有，@minapp/mobx 已经删了

**Comment by qiu8310** [comment]
是不是你的 minapp/core 或 minapp/mobx 还用的是之前的版本，没有升级到 1.x.x：

我看 BaseApp 中是没有那个报错的： https://github.com/qiu8310/minapp/blob/master/packages/minapp-core/src/system/module/BaseApp.ts#L16-L25

 MobxApp 也没那个报错：
https://github.com/qiu8310/minapp/blob/master/packages/minapp-mobx/src/lib/MobxApp.ts#L12-L21

**Comment by qiu8310** [comment]
下个版本感觉需要在 cli 中验证下本地的 core 或 mobx，是否兼容，不兼容得提醒更新

**Comment by qiu8310** [comment]
看到你一直在提问题，非常感谢你的使用！

你有看我的 1.0.0 的[更新说明](https://qiu8310.github.io/minapp/blog/2018/03/10/release-v1.html)

新版支持数据双向绑定了，这个我感觉可能对你很有用

**Comment by zaaack** [comment]
现在貌似没有了，可能是 dist 目录下的缓存。。

> 新版支持数据双向绑定了，这个我感觉可能对你很有用
双向绑定这个特性非常不错啊 ! 虽然我是 Elm架构 (单向数据流) 党。。。
