### ISSUE TITLE
@minapp/wx 在最新版的 tsc 下类型有问题

### ISSUE THREAD

**Issue by zaaack** [qiu8310/minapp#81]
```ts
[ts] 文件“/Users/z/Projects/Douban/share_not/mole/node_modules/@minapp/wx/dist/wx.d.ts”不是模块。

```

**Comment by qiu8310** [comment]
不好意思，最近太忙了。。。

我回头试试（你上个 issue 我还没处理呢）

**Comment by qiu8310** [comment]
@zaaack 你是怎么用的，我试了 ts@2.9 和 ts@next，都没有报你说的那个错误，能描述下具体怎么复现么？

**Comment by zaaack** [comment]
```import wx from '@minapp/wx'```

后来改成从 core 中引入就好了

**Comment by zaaack** [comment]
![image](https://user-images.githubusercontent.com/5233940/42030120-57337b2c-7b04-11e8-95ff-6e59e400df69.png)

**Comment by qiu8310** [comment]
是的，不能这样引用，因为 wx 是全局的，不需要单独导出一个变量，你如果想单独使用只需要这样用就行了

```
import '@minapp/wx'
```

**Comment by qiu8310** [comment]
我先关了
