### ISSUE TITLE
Animation 定义没有export方法......"调用实例的方法来描述动画。最后通过动画实例的`export`方法导出动画数据传递给组件的`animation`属性。" 

### ISSUE THREAD

**Issue by cfcodefans** [qiu8310/minapp#82]

**Comment by qiu8310** [comment]
没太理解，可以再详细描述下么，最好放个 Example

**Comment by cfcodefans** [comment]
[Animation](https://github.com/qiu8310/minapp/blob/master/packages/minapp-generator/gen/api/api-react/api-animation.d.ts) 这个类，按微信的文档，要调用一个叫‘export’的方法输出到data里，这个类这里的定义，缺少这个export方法的定义

**Comment by qiu8310** [comment]
我有意不写 export 的，原生微信中并没有 Animation 这个类，你需要使用 wx.createAnimation 来创建。

如果写了 export 在那，这样用户容易误解可以使用 new wx.Animation() 方法

**Comment by cfcodefans** [comment]
好吧， 我自己加了个接口，
    interface _Animation extends wx.Animation {
        export(): any
    }

**Comment by qiu8310** [comment]
不好意思，我理解错了

现在了解了，我下个版本想办法处理下

**Comment by qiu8310** [comment]
已经可以自动生成了
