### ISSUE TITLE
.wxml文件中存在<wxs>标签，VSCode 格式化问题

### ISSUE THREAD

**Issue by blusoul** [qiu8310/minapp#84]
## 版本说明
  OS: windows 10 1803
  VSCode:  1.24.1
  minapp:  1.6.1
## 问题描述：
*  VSCode中格式化有<wxs>标签的.wxml文件时，每次保存格式化时会在<wxs>标签内首行和尾行增加一个空行
* 去掉保存格式化，手动格式化也是如此，没有其他微信小程序类插件的冲突，其他插件不高亮
* 不知道是VSCode格式化的问题，还是插件的问题

![截图](https://i.loli.net/2018/07/03/5b3b1718cc593.png)

**Comment by qiu8310** [comment]
了解了，格式化是插件里做的，我下个版本修复

**Comment by blusoul** [comment]
@qiu8310  好，谢谢你

**Comment by qiu8310** [comment]
问题修复了，更新插件即可
