### ISSUE TITLE
所有的wx.xxxx 的异步回调 complete 事件 没有返回

### ISSUE THREAD

**Issue by mkc-doubill** [qiu8310/minapp#86]
![image](https://user-images.githubusercontent.com/16285259/42507405-a9c8d2b6-8477-11e8-84d7-073595f47cf6.png)

文档里的也没有返回值
![image](https://user-images.githubusercontent.com/16285259/42507436-c8e7cddc-8477-11e8-932f-3762d20f9aeb.png)

**Comment by qiu8310** [comment]
complete 都没有返回值吧，因为有可能有error，你要返回值需要用 success 回调

**Comment by mkc-doubill** [comment]
有的，所有的异步返回，success，fail和complete都是有返回值的
![image](https://user-images.githubusercontent.com/16285259/42547371-5bdaa1ce-84f4-11e8-910d-ea5bffe7f0a5.png)

**Comment by qiu8310** [comment]
你也不能依赖 complete 中的返回值，如果调用的是 error 回调，而不是 success 回调，那这里的返回值就可能不能满足你需求了。

还是之前说的，如果你需要使用返回值，尽量使用 success 回调，而不要去使用 complete 中的回调。

或者你使用我提供的 promise 版的 wx 接口 **wxp**

**Comment by mkc-doubill** [comment]
好的，谢谢
