### ISSUE TITLE
__webpack_require__ is not defined

### ISSUE THREAD

**Issue by AS-D** [qiu8310/minapp#87]
import * as Enumerable from 'linq'
当我尝试引入linq时，编译完在微信开发者工具下抛出异常
 __webpack_require__ is not defined 
 ReferenceError: __webpack_require__ is not defined
本人对webpack不太了解希望大神帮忙看下原因

**Comment by qiu8310** [comment]
明天我跟进一下，已经回家了

**Comment by AS-D** [comment]
嗯，先谢过

**Comment by qiu8310** [comment]
看了下，好像是我的 bug，得下个版本处理下

**Comment by qiu8310** [comment]
刚发布的 @minapp/cli@2.2.0 版修复了这个问题

**Comment by solarhell** [comment]
现有的小程序需要更新吗？

**Comment by qiu8310** [comment]
不需要，只需要更新 @minapp/cli
