### ISSUE TITLE
期望改进

### ISSUE THREAD

**Issue by EmmaCCC** [qiu8310/minapp#88]
js中微信的api 智能提示什么时候能加上，我这边一个都显示不出来是为什么

**Comment by qiu8310** [comment]
有的呢，你是用 minapp init 创建的 js 项目么？


![image](https://user-images.githubusercontent.com/1094697/42869492-c80a314e-8aa7-11e8-9dd8-bb7f4e151d1e.png)

**Comment by EmmaCCC** [comment]
啊？怎么用啊 我就直接用vscode打开硬盘上的小程序项目的

**Comment by qiu8310** [comment]
https://qiu8310.github.io/minapp/docs/doc-how-to-use-wxp-in-other-project.html
