### ISSUE TITLE
插件完全无效

### ISSUE THREAD

**Issue by Peter-90** [qiu8310/minapp#91]
不知道是不是我的插件冲突还是其他什么原因导致我装了插件后完全没有作用，大佬能指点一下吗

**Comment by qiu8310** [comment]
Readme 里有注明：

安装插件后没有出现自动补全

确保安装后有重启过 vscode
确保当前文件的格式是 wxml 或 wxml-pug 或 vue (不能看文件后缀名，因为可能在配置文件中把它们关联的其它文件格式；需要看 vscode 右下解显示的文件类型)
wxml 需要输入 < 才会触发标签补全，而 pug 中只需要输入标签名就会出来自动补全


一般第二个问题居多

**Comment by Peter-90** [comment]
@qiu8310 大佬可以了 谢谢大佬 牛逼 手动点赞 期待新的功能

**Comment by qiu8310** [comment]
比如呢，你需要什么功能？
