### ISSUE TITLE
如和将component打包成小程序支持的npm包?

### ISSUE THREAD

**Issue by NewFuture** [qiu8310/minapp#93]
小程序的npm(目前是预览版) https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html
把component文件输出到一个特定的文件夹即可。

如果以组件(component)模式进行编译，只会编译这些文件输出到dist，但是其中的依赖(tslib,@minapp/core等)不会被打包进去

**Comment by qiu8310** [comment]
现在不支持
